{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyperdx.serviceAccountName" . }}
  labels: {{- include "hyperdx.labels" . | nindent 4 }}
  annotations: {{- toYaml (merge .Values.serviceAccount.annotations .Values.commonAnnotations) | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
